### ISSUE TITLE
Update images to ubuntu 17

### ISSUE THREAD

**Issue by niemyjski** [elastic/azure-marketplace#113]
http://releases.ubuntu.com/zesty/ :)

**Comment by russcam** [comment]
I knew this was coming 😄 [We only support OSes that are part of the support matrix](https://www.elastic.co/support/matrix) in the template, because these are ones that we test on. Once Ubuntu 17 is supported, we can look at adding it but I'd be keen to close this issue now and reopen it when that happens.

**Comment by russcam** [comment]
Closing this as this won't supported in the template unless/until it's supported in the support matrix. Feel free to reopen if/when this happens 👍
