### ISSUE TITLE
Support Azure Container Deployments + Service Fabric

### ISSUE THREAD

**Issue by MedAnd** [elastic/azure-marketplace#127]
@russcam @sixeyed so imagine this if you will, a world where Elastic Search clusters can be provisioned using ARM templates but instead of creating a Linux VM Scale Set cluster, the ARM template supports creating a Docker Container cluster... 

The ability to deploy either Linux or Windows containers would be great, with a Docker Linux image or a Docker MS Nanoserver image for example. 

By the end of the year, it would be great if I could deploy ES containers into an existing Service Fabric cluster. Service Fabric would orchestrate node fail-over, scale-out (provisioning) etc alongside my other microservices. 

What do you guys think? 😃

**Comment by MedAnd** [comment]
This could be made possible by adding [support for autopilot pattern in Docker containers](https://github.com/Azure/service-fabric-issues/issues/666) in Azure Service Fabric.

**Comment by russcam** [comment]
Hey @MedAnd, I suspect if we were to look at supporting this in the future, that it would likely be a separate ARM template, as the complexity of managing deployment to choices of VMs, Service Fabric or Kubernetes/Container service would be large.

Running a complex distributed system like Elasticsearch on top of another distributed system like Service Fabric or Kubernetes is no small undertaking, moreso when you start to look at supporting features like  rolling upgrades and shard allocation awareness. 

My thought at this time is rather than keep this issue open on this repository, which is unlikely to be the end repository if such a template is developed, close it for now and look to engage further down the track if such a template is developed. If you're heading to [Elasticon Sydney](https://www.elastic.co/elasticon/tour/2018/sydney), I'd be more than happy to chat about it further in person 👍
