### ISSUE TITLE
Keeping templates in sync

### ISSUE THREAD

**Issue by hglkrijger** [elastic/azure-marketplace#13]
I notice that there are two ARM templates out there:

https://github.com/elastic/azure-marketplace
https://github.com/Azure/azure-quickstart-templates/tree/master/elasticsearch

I think they each have things the other does not. Does it make sense to keep these in sync somehow?

**Comment by russcam** [comment]
@hglkrijger I'm not sure how feasible this might be to do now at this stage, since the templates have diverged so much in the last two years. 

We have committed changes back to the quickstart template where it has made sense to do so, and will continue to make an effort to do so going forward.

Are you happy for me to close this issue?

**Comment by russcam** [comment]
Closing this issue. Feel free to reopen if you would like to discuss further 👍
