### ISSUE TITLE
artifactsBaseUrl to point to folder on local file system?

### ISSUE THREAD

**Issue by lmemmott** [elastic/azure-marketplace#136]
I'd like to run the template without having to go to github to get the files.  I'm running New-AzureRmResourceGroupDeployment like this using -TemplateFile to point to the mainTemplate.json on my local hard drive:

$ElasticsearchResult = New-AzureRmResourceGroupDeployment -Name "elasticsearch" -ResourceGroupName $ResourceGroupName -TemplateFile "Elasticsearch\mainTemplate.json" -TemplateParameterObject $clusterParameters

I seem to run into a issue with artifactsBaseUrl in mainTemplate.json.  It points to the following by default: https://raw.githubusercontent.com/elastic/azure-marketplace/master/src
Later in the script other things reference artifactsBaseUrl and then go to that URL to download files.

Is it possible everything locally instead of having to go to github for it?

**Comment by russcam** [comment]
This is not possible with the template because the referenced [linked templates](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-linked-templates) need to use a publicly available URI. It's totally possible to host all the templates somewhere else public and pass a value for `artifactsBaseUrl`. 

As far as I understand, when using `-TemplateFile`, all resources must be in the one template.
