### ISSUE TITLE
Investigate start time of ARM template

### ISSUE THREAD

**Issue by cjgeode** [elastic/azure-marketplace#17]
When creating a new cluster using the ARM template, there are two steps that take a long time.

1. Scripts running to install and start ES (15 minutes for 3 nodes)
2. Scripts running to install and start Kibana (about 15 more minutes)

The latest deployment I did with 3 data nodes and no dedicated masters took about 45 minutes.  A similar deployment, with timing, can be seen in the cjfebresourcegroup under the elastic azure account. This behavior is consistent across different data centers - I tried both West Europe and West US.

**Comment by Mpdreamz** [comment]
I added some more logging so we can gain insights in the time each step in the installation sequence takes. My hunch is that raid 0'ing the disk is taking a loooong time. 

@hglkrijger is working on adding support for Azure AFS bases disks (SMB 2.1 shares) here: https://github.com/Azure/azure-quickstart-templates/commit/6de83a05432e482310c8cf18ab6643dc23fffdc7 this could be interesting for us to expose as well.

**Comment by Mpdreamz** [comment]
Here is an example output of the logging for the elasticsearch install bash script:

https://gist.github.com/Mpdreamz/2f1859582132235607d2

Its the output of a grep for all **our** timestamped messages e.g:

> 2016/02/11 13:14:54 [11022016-13:14:23] installing ntp deamon
2016/02/11 13:14:54 [11022016-13:14:31] installed ntp deamon and ntpdate

The first timestamp is azure's and it snapshotted timestamp of the buffer received up till that point. Which stays pretty static. The second one is our timestamp (in between the brackets) this more accurately depicts the running times of various stages. 

Unsuprisingly raid0'ing the disks takes a bit 

> 2016/02/11 13:14:54 [11022016-13:14:31] starting to RAID0 the attached disks
2016/02/11 13:15:24 [11022016-13:14:31] installed ntp deamon and ntpdate
2016/02/11 13:15:24 [11022016-13:14:31] starting to RAID0 the attached disks
2016/02/11 13:15:54 [11022016-13:14:31] installed ntp deamon and ntpdate
2016/02/11 13:15:54 [11022016-13:14:31] starting to RAID0 the attached disks
2016/02/11 13:16:24 [11022016-13:14:31] installed ntp deamon and ntpdate
2016/02/11 13:16:24 [11022016-13:14:31] starting to RAID0 the attached disks
2016/02/11 13:16:54 [11022016-13:16:35] finished RAID0'ing the attached disks
2016/02/11 13:16:54 [11022016-13:16:35] Adding apt repository for java 8
2016/02/11 13:16:54 [11022016-13:16:38] updating apt-get
2016/02/11 13:17:24 [11022016-13:16:35] finished RAID0'ing the attached disks

The output is not fully synchronous due to the way logs are written to extension.log in azure but we can see that raiding starts at `13:14:31` and ends `13:16:35` a couple of seconds over `2m`. 

More interestingly however is that according to the output installing java8 takes a whopping `4m`

> 2016/02/11 13:17:24 [11022016-13:16:35] Adding apt repository for java 8
2016/02/11 13:17:24 [11022016-13:16:38] updating apt-get
2016/02/11 13:17:24 [11022016-13:16:56] updated apt-get
2016/02/11 13:17:24 [11022016-13:16:57] Installing Java
2016/02/11 13:21:09 [11022016-13:20:59] Installed Java

See last 2 lines, this was a suprise.

So the total runtime of the script is: 7 and a half minutes but even if we paralize parts we can only bring it down to 4, which is not encouraging.

**Comment by Mpdreamz** [comment]
One thing thats now been committed that will save some time is that the kibana node no longer depends on the data nodes being deployed (kibana has excellent retry mechanisms ootb). 

So kibana and the data/client/master nodes are now all deployed in parallel

**Comment by Mpdreamz** [comment]
On average it takes 3-4 minutes for the deploy script to kick in which takes 7 to 10 minutes to deploy of which much is spent installing java from the community provided apt-get repository (4-6 minutes).

I think kibana no longer waiting for data-nodes to finish is a huge win, I tried to shave off 2-3 minutes from the deploy by paralleling some commands but this brings all sorts of complexity I'm not sure is worth it.

**Comment by Mpdreamz** [comment]
Closing this since the time consuming parts are out of our control and deploy times are way less irratic now that we forcefully restart `waagent` during the install so that azure does not lose connection to the deployment process and thus waiting for ServerTimeout.
