### ISSUE TITLE
Using External Load Balancer causes Kibana to be misconfigured

### ISSUE THREAD

**Issue by cjgeode** [elastic/azure-marketplace#18]
If you set up a cluster using the ARM template, and choose External load balancer at the very end, and also choose to install Kibana, Kibana will end up misconfigured. This is similar to this issue:

https://github.com/elastic/azure-marketplace/issues/14

And will manifest itself the same way.  The workaround is to SSH into the VM and change the Kibana configuration by hand.

**Comment by Mpdreamz** [comment]
This has now been fixed albeit with a moderate hack. 

When selecting an external loadbalancer we now deploy 2 loadbalancers, 1 internal and 1 external. Due to a limitation of ARM though these two loadbalancers can not both operate on the same backend port 9200. 

There for the elasticsearch nodes reroute 9201 to 9200 on the same machine using iptables allowing the external loadbalancer to use 9201 as the backend ports (while still publicly listening on 9200)

Now kibana can always assume the internal loadbalancer will be deployed at 10.0.0.100 and we can keep all communication from kibana to elasticsearch internal too which is nice.

I think in the future we need to get rid of the external loadbalancer alltogether:

We now have too many public options, jumpbox/kibana/external loadbalancer

I would love to make the jumpbox non optional but allow you to optionally install kibana and a public proxy (nginx/haproxy) with SSL for both the proxy and kibana using letsencrypt. Will open a new ticket for this.

**Comment by troydemonbreun** [comment]
@Mpdreamz  In which version was this changed? Thanks!

**Comment by Mpdreamz** [comment]
Sadly not in any published version just yet, we are working on getting another version pushed to the marketplace soon. The version on the market place is still the one from december/january so quite a few fixes and features are pending!

**Comment by troydemonbreun** [comment]
Thanks for the quick response!
