### ISSUE TITLE
Add flexibility to add load balancers for master and data node

### ISSUE THREAD

**Issue by mayuvara** [elastic/azure-marketplace#244]
Add flexibility to add load balancers for master and data node

**Comment by russcam** [comment]
Data nodes are included in the backend pool of the load balancers, unless client nodes are deployed, in which case client nodes are configured in the backend pool. 

Master nodes shouldn't receive requests, and instead should be left to handle things like managing cluster state. Because they shouldn't handle requests, they don't need a load balancer in front.

Could you provide some detail for proposing a load balancer for master nodes @mayuvara?

**Comment by mayuvara** [comment]
We have an indexing-intensive pattern for our use case. The way we understand Elasticsearch is that even if the indexing requests go to the data nodes, the data nodes would eventually need to talk to the master nodes for shard/node assignment. Please correct me here, if you think otherwise.

**Comment by russcam** [comment]
All nodes communicate with each other on the transport layer, and this is handled by Elasticsearch itself. Dedicated master nodes should not receive requests, they should be left to manage cluster state, leader election, etc.

Take a look at the docs on [master nodes](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/modules-node.html#master-node), specifically

> While master nodes can also behave as coordinating nodes and route search and indexing requests from clients to data nodes, it is better not to use dedicated master nodes for this purpose. It is important for the stability of the cluster that master-eligible nodes do as little work as possible.

If you're not using dedicated master nodes in the template then all data nodes will be master-eligible and will receive requests.

I'm closing this issue as dedicated master nodes do not require a load balancer in front.
