### ISSUE TITLE
Add ability to replace default values in the yml files

### ISSUE THREAD

**Issue by mayuvara** [elastic/azure-marketplace#250]
Add ability to replace values existing in the elasticsearch.yml, kibana.yml files.
The template does not let replacement of default settings in yml files
for eg. kibanaadditionalyaml, esadditionalyaml could replace properties, if they exist.

**Comment by russcam** [comment]
This is intentional, to mitigate a user from making changes that would invalidate a template deployment.
Which values are you looking to replace?

**Comment by mayuvara** [comment]
logging.silent: true gets added by default in kibana.yml. I don’t see a way to set server.ssl.certificate, server.ssl.key other than passing the cert blobs.
Some of the parameters get translated to properties in the yml files. Is there documentation that explains this?

**Comment by russcam** [comment]
> logging.silent: true gets added by default in kibana.yml. 

This is done so that the Kibana log files do not grow and consume all resources. Unlike Elasticsearch and Logstash, Kibana does not have rollover retention policy to delete older log files. We could probably make the default `logging.quiet: true` here, to suppress all logging output other than error messages.

> I don’t see a way to set server.ssl.certificate, server.ssl.key other than passing the cert blobs.
Some of the parameters get translated to properties in the yml files. Is there documentation that explains this?

`server.ssl.certificate` and `server.ssl.key` configuration are set when passing cert blobs and keys for Kibana TLS configuration. [There's documentation for which parameters to use to configure TLS for Kibana](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-security.html#tls-kibana)

**Comment by russcam** [comment]
I'll look to update Kibana's logging policy to `logging.quiet: true`

**Comment by russcam** [comment]
#296 is merged to change kibana logging to quiet, 

I'm going to close this issue as "won't fix". Certain yml configuration settings cannot be set using the additionalYaml parameters intentionally, to mitigate a user from making changes that would invalidate a template deployment.
