### ISSUE TITLE
Correct number of disks do not deploy with cluster and are occasionally lost on restart

### ISSUE THREAD

**Issue by JoeBerg8** [elastic/azure-marketplace#299]
When the variables   `"vmDataDiskCount":{"value":3},"vmDataDiskSize":{"value":"32GiB"}` are set in the script, I have often observed the number of disks mounted to the VM to be less than the number specified in the parameter.   However, the portal UI shows 3 attached to the VM but the filesystem shows less.  

Also, when the VMs are stopped and restarted, the data in some of the disks inconsistently disappears. 

See images below: 

ls -lrt gives below:
<img width="368" alt="Screen Shot 2019-07-02 at 3 01 31 PM" src="https://user-images.githubusercontent.com/15018775/60545104-4249f680-9ce8-11e9-8583-92ff3a9a0021.png">

-------------------------------------------------------------------------------------------
![MicrosoftTeams-image](https://user-images.githubusercontent.com/15018775/60545116-4b3ac800-9ce8-11e9-80ee-899903abbd43.png)

**Comment by russcam** [comment]
>  I have often observed the number of disks mounted to the VM to be less than the number specified in the parameter. 

Could this be that the number of disks specified is more than the VM can have attached, so, [per the docs](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-data-disks.html), the template takes the minimum value of these two, i.e.

```
Math.min(vmDataDiskCount, data node VM SKU maximum attached disks)
```

For example, if I perform a deployment with the following config:

![image](https://user-images.githubusercontent.com/208231/60549334-e8891100-9d67-11e9-812b-aa664f613e40.png)

Since `Standard DS1 v2` VM SKUs can only have a maximum of 4 attached data disks, I get

![image](https://user-images.githubusercontent.com/208231/60549381-0b1b2a00-9d68-11e9-8e0c-58bec464d079.png)

for each data node. So, I asked for 6 attached disks per `Standard DS1 v2` VM, but only 4 were attached to each VM, the maximum for the VM SKU.

Ideally, we would want to cap the maximum number of disks that can be selected by the user based on the chosen VM SKU, but the Azure Marketplace UI does provide sufficient control to do this. Rather than fail deployments in this scenario, we opted to take the above strategy in the UI and template, and document the behaviour.

> Also, when the VMs are stopped and restarted, the data in some of the disks inconsistently disappears.
> See images below:
> ls -lrt gives below:

`ls -lrt` lists information about directories and contents. A RAID 0 array is configured across all of the attached disks, mounted at the next available mountpoint at `/datadisks/disk*`. For example, running that command on the VM just deployed with 4 attached disks

![image](https://user-images.githubusercontent.com/208231/60550654-06587500-9d6c-11e9-8f02-8631b4e9ee34.png)

But if the block devices are listed with [`lsblk`](https://linux.die.net/man/8/lsblk)

![image](https://user-images.githubusercontent.com/208231/60550745-5df6e080-9d6c-11e9-8d9d-5da11da41f41.png)

Four devices, `sdc` - `sdf`, the attached managed disks, make up the RAID 0 array mounted at `/datadisks/data1`. `sda` is the OS disk and `sdb` mounted at `/mnt` is the tempdisk.

The RAID 0 array will be maintained through reboots. An entry is added to `/etc/mdadm/mdadm.conf` for the RAID array

```sh
russ@data-2:~$ sudo cat /etc/mdadm/mdadm.conf
# mdadm.conf
#
# Please refer to mdadm.conf(5) for information about this file.
#

# by default (built-in), scan all partitions (/proc/partitions) and all
# containers for MD superblocks. alternatively, specify devices to scan, using
# wildcards if desired.
#DEVICE partitions containers

# auto-create devices with Debian standard permissions
CREATE owner=root group=disk mode=0660 auto=yes

# automatically tag new arrays as belonging to the local system
HOMEHOST <system>

# instruct the monitoring daemon where to send mail alerts
MAILADDR root

# definitions of existing MD arrays

# This file was auto-generated on Fri, 28 Jun 2019 09:37:10 +0000
# by mkconf $Id$
ARRAY /dev/md/0 metadata=1.2 name=data-2:0 UUID=103be0b7:2b0a1644:0c41a7e9:a433b090
```

and an entry added to `/etc/fstab` for the filesystem

```sh
russ@data-2:~$ sudo cat /etc/fstab
# CLOUD_IMG: This file was created/modified by the Cloud Image build process
UUID=01909065-0362-439c-9af2-29d0fc837f6b       /        ext4   defaults,discard        0 0
/dev/disk/cloud/azure_resource-part1    /mnt    auto    defaults,nofail,x-systemd.requires=cloud-init.service,comment=cloudconfig                        02
UUID="528fad2c-ae06-4999-8642-714bd976208e"     /datadisks/disk1        ext4    noatime,nodiratime,nodev,noexec,nosuid,nofail                            1 2
```

Do you see these on `plivedata-6` VM?

**Comment by JoeBerg8** [comment]
Thanks for the detailed response @russcam . This all makes perfect sense and I do see all of the disks when I run `lsblk`.  My `/etc/mdadm/mdadm.conf` and `/etc/fstab` files also contain the same information you posted above.  

So, my part of my confusion above was due to a lack of understanding on my part.  But your post really cleared up my confusion about how to see the correct number mounted disks. 

Still one remaining question I have:  why did the `/datadisks` directory randomly get wiped out after a reboot?  I had no issues with this for about two weeks and two nights ago that directory seemed to get wiped clean after a reboot for three nodes in my cluster.  As a result, elasticsearch failed to start on those three nodes and therefore would not join the cluster.

Thanks.

**Comment by russcam** [comment]
> Still one remaining question I have: why did the /datadisks directory randomly get wiped out after a reboot?

When you say wiped out, do you mean it didn't exist after reboot, or that it did exist but was empty? 

> a reboot for three nodes in my cluster. 

Did you reboot the VMs one at a time, waiting for each to come up, and did you have sufficient number of replicas to keep the cluster operable during reboot?

If you still have the VM running, I would have a look in `/var/log/syslog` to see if there are any entries in it related to mdadm or the raid array.

**Comment by JoeBerg8** [comment]
`/datadisks` existed and `/disk1` directory existed inside of it, but directories inside of `/disk1` that you'd expect to see (`/elasticsearch` and `/lost+found`) did not exist there. 

I rebooted the three VMs at the same time, and did have sufficient number of replicas.

I'll check the sys log.  

Is it necessary to reboot one at a time?

**Comment by russcam** [comment]
> Is it necessary to reboot one at a time?

It depends on the operation, but not necessary. Use the [full cluster restart upgrade](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/restart-upgrade.html) as a guide for shutting down and restarting, stopping Elasticsearch running using systemd (or [monit, if using template version less than 6.4.2](https://www.elastic.co/guide/en/elastic-stack-deploy/6.3/azure-arm-template-elasticsearch.html)) :

```sh
sudo systemctl stop elasticsearch.service
```

If you haven't configured it already, I would strongly suggest snapshotting regularly using Azure Repository plugin, which [can be configured on deployment of the template](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-plugins.html#azure-repository).

Let me know if there's anything of interest in the sys log.

**Comment by JoeBerg8** [comment]
Sounds good @russcam and thanks for the help.  I will close this for now and make the recommendations you have provided.
