### ISSUE TITLE
Deployment error: When processing VM extension

### ISSUE THREAD

**Issue by AnilSunkesula** [elastic/azure-marketplace#355]
We are trying deploy Elasticsearch(Self-Managed) using Azure console. Selected existing Virtual network and Subnet  which are in a different resource group. Deployment is failed while processing VM extension. We are getting below error for all data node VM extensions.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'script'. Error message: \\\"**Enable failed: processing file downloads failed: failed to download file[0]: failed to download file: http request failed: Get [REDACTED] dial tcp 13.107.246.10:443: i/o timeout**\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot \"\r\n }\r\n ]\r\n }\r\n}"}]}

Could you please let us know if we need to allow any NSG rules on the existing subnet?

**Comment by russcam** [comment]
The template assumes that VMs onto which software is deployed can connect to the public internet, in order to download the Elastic Stack packages from `https://artifacts.elastic.co` and supporting Ubuntu packages through apt get. For example, for Elasticsearch

https://github.com/elastic/azure-marketplace/blob/fb6690264515d8906d565c072ea8ac2830dbcb7c/src/scripts/elasticsearch-install.sh#L387-L388

and packages

https://github.com/elastic/azure-marketplace/blob/fb6690264515d8906d565c072ea8ac2830dbcb7c/src/scripts/elasticsearch-install.sh#L1137-L1163

The template takes care of this for a new vnet but if you have an existing vnet with an NSG in place, it'll need to allow this outbound traffic for the template to complete successfully.
