### ISSUE TITLE
"Transport SSL must be enabled if security is enabled on a [basic] license" - how to disable correctly?

### ISSUE THREAD

**Issue by janegilring** [elastic/azure-marketplace#384]
Scenario: An ELK cluster with 3 masters and 3 data nodes was deployed using the ARM template. All data nodes have 1 data disk (500 GB). SSL was not enabled.

Due to a demand for more disk space, I logged into the Kibana portal to verify if everything was healthy before starting. It turned out the trial licence had expired, so I downgraded to the Basic license .

When trying to expand the data disk on the first data node - the node did not join the cluster after shutting it down, expanding the disk and starting it back up.

After looking into the logs on the node who failed to join the cluster, I found this in systemctl status elasticsearch.service:
```
Process: 1548 ExecStart=/usr/share/elasticsearch/bin/systemd-entrypoint -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=78)
Main PID: 1548 (code=exited, status=78)

Feb 01 13:26:45 dev-data-2 systemd[1]: Starting Elasticsearch...
Feb 01 13:27:11 dev-data-2 systemd-entrypoint[1548]: ERROR: [1] bootstrap checks failed
Feb 01 13:27:11 dev-data-2 systemd-entrypoint[1548]: [1]: Transport SSL must be enabled if security is enabled on a [basic] license. Please set [xpack.security.tr
Feb 01 13:27:11 dev-data-2 systemd-entrypoint[1548]: ERROR: Elasticsearch did not exit normally - check the logs at /var/log/elasticsearch/elementselkdev.log
Feb 01 13:27:11 dev-data-2 systemd[1]: elasticsearch.service: Main process exited, code=exited, status=78/n/a
Feb 01 13:27:11 dev-data-2 systemd[1]: Failed to start Elasticsearch.
```

var/log/elasticsearch/elementselkdev.log:
```
21-02-01T13:27:10,120][INFO ][o.e.n.Node               ] [dev-data-2] initialized
[2021-02-01T13:27:10,121][INFO ][o.e.n.Node               ] [dev-data-2] starting ...
[2021-02-01T13:27:10,271][INFO ][o.e.t.TransportService   ] [dev-data-2] publish_address {10.240.14.10:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}, {10.240.14.10:9300}
[2021-02-01T13:27:10,984][INFO ][o.e.b.BootstrapChecks    ] [dev-data-2] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2021-02-01T13:27:11,006][ERROR][o.e.b.Bootstrap          ] [dev-data-2] node validation exception
[1] bootstrap checks failed
[1]: Transport SSL must be enabled if security is enabled on a [basic] license. Please set [xpack.security.transport.ssl.enabled] to [true] or disable security by setting [xpack.security.enabled] to [false]
[2021-02-01T13:27:11,027][INFO ][o.e.n.Node               ] [dev-data-2] stopping ...
[2021-02-01T13:27:11,046][INFO ][o.e.n.Node               ] [dev-data-2] stopped
[2021-02-01T13:27:11,046][INFO ][o.e.n.Node               ] [dev-data-2] closing ...
[2021-02-01T13:27:11,068][INFO ][o.e.n.Node               ] [dev-data-2] closed
[2021-02-01T13:27:11,069][INFO ][o.e.x.m.p.NativeController] [dev-data-2] Native controller process has stopped - no new native processes can be started
```

SSL was not enabled when deploying the cluster, and since this is an isolated dev environment we are fine running without encryption.

What is the procedure to correctly disable SSL?
Set xpack.security.enabled to false in the config file on all masters and data nodes, stop all VMs and then start them again?

After doing so I suppose expanding the disks is trivial, or do we need to do something on the Elastic side as well for the expanded space to become available? (besides expanding the file system, that is)

**Comment by russcam** [comment]
Rather than disabling TLS for the Elasticsearch Transport layer, I would recommend securing the Transport layer. One approach is to use [elasticsearch-certutil](https://www.elastic.co/guide/en/elasticsearch/reference/current/certutil.html) to [create a CA certificate](https://www.elastic.co/guide/en/elasticsearch/reference/current/certutil.html#certutil-ca), then use this CA certificate to create a certificate for each Elasticsearch node. This can be done for all nodes at once by [creating a YAML file and passing this to elasticsearch-certutil](https://www.elastic.co/guide/en/elasticsearch/reference/current/certutil.html#certutil-silent) - you'll want to keep the CA for future, in the event you want to add new nodes in future, so pass the `--keep-ca-key`. For each certificate for each node, you'll likely want to include the hostname as a DNS entry and the IP address. As an _example_ yaml file,

```yml
instances:
  - name: "dev-master-0" 
    ip: 
      - "10.0.0.5"
    dns: 
      - "dev-master-0"
  - name: "dev-master-1"
    ip:
      - "10.0.0.6"
    dns: 
      - "dev-master-1"
  - name: "dev-master-2"
    ip:
      - "10.0.0.7"
    dns: 
      - "dev-master-2"
  - name: "dev-data-0"
    ip:
      - "10.0.0.8"
    dns: 
      - "dev-data-0"
  - name: "dev-data-1"
    ip:
      - "10.0.0.9"
    dns: 
      - "dev-data-1" 
  - name: "dev-data-2"
    ip:
      - "10.0.0.10"
    dns: 
      - "dev-data-2" 
```

Which can generate all certificates in a zip file with

```
.\elasticsearch-certutil cert --silent --in instances.yml --out certs.zip --pass testpassword --keep-ca-key --ca-pass catestpassword
```

With certificates created and each respective certificate for each node copied to the node, add [Security settings for the Transport layer](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#transport-tls-ssl-settings) in `/etc/elasticsearch/elasticsearch.yml`. This would look something like

```yml
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.keystore.path: <path to TLS certificate for this node>
xpack.security.transport.ssl.truststore.path: <path to TLS certificate for this node>
```

where `<path to TLS certificate for this node>` is the path to where the TLS certificate generated for this Elasticsearch node was copied (ensure `elasticsearch:elasticsearch` can access it).

With configuration added, restart the node

```
systemctl restart elasticsearch.service
```

[Check out what the installation script does on each node when a CA cert is passed to secure the Transport layer](https://github.com/elastic/azure-marketplace/blob/e405aa839b90b88ea8e1c973d62f596cd10e76bf/src/scripts/elasticsearch-install.sh#L854-L962), for reference.

----

If you _really_ want to disable TLS for the Transport layer, then set `xpack.security.transport.ssl.enabled: false` in  `/etc/elasticsearch/elasticsearch.yml` and restart the node. There may be ramifications to doing this that I am not aware of e.g. specific features may be dependent on it being enabled.

----

> After doing so I suppose expanding the disks is trivial, or do we need to do something on the Elastic side as well for the expanded space to become available? (besides expanding the file system, that is)

Multiple data disks per node are configured in a RAID 0 configuration, but since there is only one data disk per node, it will have just been partitioned and mounted. Assuming that expanding disks within Azure does not impact the existing data or operation of the disk, I would expect Elasticsearch to pick it up, though this is not something I've tested.

**Comment by janegilring** [comment]
Excellent, thanks a lot! That did the trick, and expanding the disk also went well - Elasticsearch could also see the additional space after expanding the partition and filesystem within the VMs.

I`ll close the issue, but was wondering if you know the answer to a final question: When doing maintenance on the nodes (both masters and data nodes) such as patching the operatingsystem, are there any need to put the nodes in some sort of maintenance mode from a cluster/Elastic perspective? Or is it ok to simply reboot the nodes as needed as long as only one at a time rebooted?

**Comment by russcam** [comment]
Glad you got it sorted 🎉 

> When doing maintenance on the nodes (both masters and data nodes) such as patching the operatingsystem, are there any need to put the nodes in some sort of maintenance mode from a cluster/Elastic perspective? Or is it ok to simply reboot the nodes as needed as long as only one at a time rebooted?

Once deployed, the upgrade guidance for Azure follows [the standard upgrade guidance for  a self-managed cluster.](https://www.elastic.co/guide/en/elastic-stack/current/upgrading-elastic-stack.html). For patching the operating system where a reboot is required, I would advise [performing a graceful shutdown of Elasticsearch with systemd](https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html#upgrade-node) on a node at a time. This assumes that you have sufficient shards and replica shards such that the cluster remains operable whilst each node is shutdown and patched in turn.
