### ISSUE TITLE
No options for number of data disk and disk size brings error

### ISSUE THREAD

**Issue by yaoxiaotong** [elastic/azure-marketplace#50]
I'm deploying 10 data nodes with DS3_v2 which have 8 premium data disks each by default. 
It need totally 80 TB premium storage. 

However, Azure's premium storage limit per account is 35 TB. It is not possible to deploy that. 

I walk around this by first deploy with smaller vm DS1_v2, remove the disks and then upgrade it to DS3_v2. 

Is it possible to provide the option for data disk? 
In our case, we only need one 512GB data disk.

**Comment by Mpdreamz** [comment]
We create multiple storage accounts for attached disks so you should be able to create bigger clusters like that, we will look into confirming this!

The biggest cluster we deployed had 120 nodes with 2TB totalling 240TB.

Being able to choose disk size in the template might be a nice option since smaller disks are also cheaper (albeit with less performance).

**Comment by niemyjski** [comment]
I think this can be closed, @yaoxiaotong I'd try the latest code as a ton of work has been done on this.

**Comment by yaoxiaotong** [comment]
@niemyjski 
I actually raised two issue:
1) no option for attached disk - I tried two weeks ago, there were still no option for this
2) deployment on DS3_v2 failed because of Azure storage account limit. - I did not check this

I'm happy to close it if it is solved or it is decided not to solve.

**Comment by russcam** [comment]
@yaoxiaotong through the command line, it is now possible since 08e6ab2ffc6ccb6ddafe36f69f29515aeb5d1c72 to specify:

- number of disks to attach to each data node in RAID 0 setup. When 1 disk is selected, the disk is not RAIDed. When 0 disks are selected, no disks will be attached to each data node; instead, the temporary disk will be used to store Elasticsearch data. *The temporary disk is ephemeral in nature and not persistent.*
- disk size of each attached disk, `Large` (1024Gb), `Medium` (512Gb) or `Small` (128Gb). Default is Large. 
- storage account type of the attached disks. Choose either `Default` or `Standard`. The `Default` storage account type will be Premium Storage for VMs that support Premium Storage and Standard Storage for those that do not.

Take a look at the [README parameters](https://github.com/elastic/azure-marketplace#parameters) for more details.

These parameters are not exposed in the Marketplace UI in order to keep it a simple to use first time experience.

I'm closing this issue.
