### ISSUE TITLE
Add ability to pick base kibana features

### ISSUE THREAD

**Issue by niemyjski** [elastic/azure-marketplace#79]
It would be nice if I could just say install kibana without having to also install shield and all the other features. Ideally if I could select the free features (watcher and kibana that would be awesome :).

**Comment by niemyjski** [comment]
@Mpdreamz I said to install kibana but no es plugins (I don't want xpack). But there seems to be an issue. I got the node created but kibana isn't installed (it's just an empty node).

**Comment by russcam** [comment]
@niemyjski it's possible to install Kibana without X-Pack by deploying the template from the GitHub repository:

```powershell
$templateVersion = "5.6.6"
$templateUrl = "https://raw.githubusercontent.com/elastic/azure-marketplace/$templateVersion/src"
$mainTemplate = "$templateUrl/mainTemplate.json"
$location = "Australia Southeast"
$resourceGroup = "without-xpack"
$name = "elasticsearch"

$templateParameters = @{
    "artifactsBaseUrl"= $templateUrl
    "esClusterName" = $name
    # Don't install the X-Pack plugins
    "xpackPlugins" = "No"
    "adminUsername" = "russ"
    "authenticationType" = "password"
    "adminPassword" = "Password1234"
}

New-AzureRmResourceGroup -Name $resourceGroup -Location $location

$deployment = New-AzureRmResourceGroupDeployment -Name $name -ResourceGroupName $resourceGroup `
    -TemplateUri $mainTemplate -TemplateParameterObject $templateParameters

# Open web browser with Kibana when complete
Start-Process $deployment.Outputs.kibana.Value
```
This will deploy Elasticsearch and Kibana but will not install X-Pack plugins on either. https://github.com/elastic/azure-marketplace/commit/8307f562f135cb5f2019cbc37b3b353bdee6b18a fixed a bug where installation was dependent on installing plugins.

If you were looking to install a free basic license for X-Pack, then the easiest way to do so would be to

1. deploy with the 30 day trial license of X-Pack
2. [register for a free basic license](https://register.elastic.co/)
3. [apply the license to the cluster](https://www.elastic.co/guide/en/x-pack/current/installing-license.html)
4. restart each node in turn on the cluster
5. restart kibana

There is #11 to allow a license to be applied as part of deployment to make this simpler in future.

I'm going to close this issue because I think the original issue has been resolved.
